### ISSUE TITLE
Book: Domain-Driven Design Distilled, by Vaughn Vernon

### ISSUE THREAD

**Issue by octavian-nita** [SAP/curated-resources-for-domain-driven-design#12]
Hi guys,

Here's another book from Vaughn Vernon: [Domain-Driven Design Distilled](https://www.amazon.de/Domain-Driven-Design-Distilled-Vaughn-Vernon/dp/0134434420). Relatively small and terse, I don't know where I would place it: under the **_201_** section or even under **_Further Goodies_**.

**Comment by lechnerc77** [comment]
@octavian-nita Thanks for bringing this up. 
I would propose to put it as an additional entry under **201**.
@mr-flannery @neolytian : What Do you think?

**Comment by mr-flannery** [comment]
I think I'd put it into the 201 section. My understanding of 201 right now is "I'm hooked, please give me something that helps me make a higher-level holistic sense of DDD" (or something among those lines). If that is what this book delivers (and the Amazon page makes it look this way, but I haven't read it myself), than it sounds like a good fit to me.

**Comment by octavian-nita** [comment]
Alright -- thanks, guys!

I'll fork and do a PR for you to check.
