### ISSUE TITLE
Should frameworks be curated, too?

### ISSUE THREAD

**Issue by octavian-nita** [SAP/curated-resources-for-domain-driven-design#13]
I haven't noticed any sections or references to frameworks that explicitly support or promote a DDD approach when architecting applications. Is it deliberate?

If that's not on purpose, here's a Java one I've been using so far: [Axon Framework](https://www.axoniq.io/axoniq-products#tab1) and its view on the matter: [Domain-Driven Design](https://developer.axoniq.io/domain-driven-design/overview).

**Comment by lechnerc77** [comment]
I will convert this into a GitHub discussion as this is better fitting for this sort of content
