### ISSUE TITLE
[BUG] Doubled/wrong hyperlink "50.000 Orange Stickies Later"

### ISSUE THREAD

**Issue by bananaware-was-taken** [SAP/curated-resources-for-domain-driven-design#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which area of the resources should be enhanced?

DDD & Event Storming 101 - Let's get things started

### Bug description

Hello,
the hyperlink of the third clip "[50.000 Orange Stickies Later](https://youtu.be/mLXQIYEwK24)" seems to be a copy+paste error.
It is the same hyperlink as the second video.

I assume the actual hyperlink to "50.000 stickies later" would be: [https://www.youtube.com/watch?v=NGXl1D-KwRI](https://www.youtube.com/watch?v=NGXl1D-KwRI).

**Comment by lechnerc77** [comment]
Thanks for bringing that to our attention. A fix is on its way

**Comment by lechnerc77** [comment]
Fix is deployed, thanks again for raising the issue
