### ISSUE TITLE
[FEATURE REQUEST] Proposals for additional Event Storming videos

### ISSUE THREAD

**Issue by bananaware-was-taken** [SAP/curated-resources-for-domain-driven-design#17]
### Area of the resources that should be enhanced?

DDD & Event Storming 201 - Give me more

### Link to resource

https://www.youtube.com/watch?v=fGm62ra_mQ8

### Description

"100.000 Orange Stickies Later"
Alberto Brandolini's talks get clearer and better to understand over time.
I consider this talk a better introduction to the topic than the previous talks - on the other hand, I might have understood Event Storming better from this talk because I saw the others before 😄

**Comment by mr-flannery** [comment]
Thanks for the proposal! 

> I might have understood Event Storming better from this talk because I saw the others before

I also recently read "everyone's favorite explanation of monads is the third one they read" 😛 That being said, I still have to watch the online event storming video (see #18 ), so I'm leaving this one for you two to decide.

**Comment by lechnerc77** [comment]
@bananaware-was-taken fyi: we did not forget this request, just did not yet manage to watch the referenced talk.

**Comment by bananaware-was-taken** [comment]
> @bananaware-was-taken fyi: we did not forget this request, just did not yet manage to watch the referenced talk.

Hello @lechnerc77 , Thank you for the update. Take your time. No need to rush. After all, it is just a proposal and not urgent.

**Comment by lechnerc77** [comment]
PR merged, README is updated
