### ISSUE TITLE
[FEATURE REQUEST] Additional resource on remote Event Storming - with the master himself

### ISSUE THREAD

**Issue by bananaware-was-taken** [SAP/curated-resources-for-domain-driven-design#18]
### Area of the resources that should be enhanced?

DDD & Event Storming 301 and beyond - Going all in

### Link to resource

https://www.youtube.com/watch?v=v4xLxmpAFdI

### Description

This video is the lessons learnt, introduction, and comparison between in-person ES and remote ES.
It is more structured than the "online event storming" clip that is already among the resources. 

My observation/opinion: 
1) The "trying out online event storming" video is rather unstructured, long, and partly with technical issue. Nonetheless, the commentaries and discussions are interesting on the meta-level and they could be interesting for moderators.
2) To get an introduction for starters and practitioners, the proposed clip would be better.

Thanks and regards!

**Comment by lechnerc77** [comment]
@mr-flannery @neolytian What Do you think? Looks like a nice addition fitting into the 301 area

**Comment by mr-flannery** [comment]
Thanks for the proposal! I'll try to watch this on the side today. I agree that "trying out online Event Storming" is somewhat rambly, I'm not sure whether I finished that myself. If the proposed video is more helpful, we could also move "trying out.." to the Further Goodies section.

**Comment by mr-flannery** [comment]
@bananaware-was-taken Thanks for the addition, I think this is an interesting talk! I opened a PR that adds this talk alongside some comments. Let me know what you think!
