### ISSUE TITLE
[BUG] Definition of Domain Roles

### ISSUE THREAD

**Issue by palek** [SAP/curated-resources-for-domain-driven-design#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which area of the resources should be enhanced?

Further DDD Goodies

### Bug description

The definition of Domain Roles of the Bounded Context Canvas in the _Domain-Driven Design Kata_ is incorrect. It isn't about the collaborating entities and the stakeholder's expectations but rather about its role in the whole system.

Based on the referenced post it characterises the behaviour of the bounded context, and helps avoid coupling of responsibilities by identifying the different roles the context plays.

https://virtualddd.com/learning-ddd/ddd-crew-bounded-context-canvas#domain-roles

**Comment by mr-flannery** [comment]
Hi @palek, thanks for reporting the issue! We're a stretched a little thin on time this week, so we'd also happily accept a PR for this :) Otherwise, @neolytian, do you mind taking a look once you're back?

**Comment by neolytian** [comment]
Fixed with https://github.com/SAP/curated-resources-for-domain-driven-design/pull/34
